# Generated by Django 4.2.1 on 2024-09-03 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_client_created_at_client_updated_at_and_more'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='id_professional',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='person.professional', verbose_name='Profissional'),
            preserve_default=False,
        ),
    ]
