# Generated by Django 4.2.1 on 2024-09-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_service_id_professional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='average_duration',
            field=models.TimeField(blank=True, null=True, verbose_name='Duração Média'),
        ),
        migrations.AlterField(
            model_name='service',
            name='average_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Médio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
