# Generated by Django 4.2.1 on 2024-09-03 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_client_created_at_client_updated_at_and_more'),
        ('schedule', '0003_alter_service_average_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('closed', models.BooleanField(default=False, verbose_name='Pacote concluído')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.client', verbose_name='Cliente')),
                ('id_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.professional', verbose_name='Profissional')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='average_duration',
            field=models.TimeField(blank=True, null=True, verbose_name='Duração Média (HH:MM:SS)'),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor')),
                ('status', models.CharField(choices=[('1', 'Agendado'), ('2', 'Em andamento'), ('3', 'Concluído'), ('4', 'Cancelado')], default='2', max_length=1, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.client', verbose_name='Cliente')),
                ('id_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.professional', verbose_name='Profissional')),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.service', verbose_name='Serviço')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('status', models.CharField(choices=[('1', 'Agendado'), ('2', 'Em andamento'), ('3', 'Concluído'), ('4', 'Cancelado')], default='2', max_length=1, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.package', verbose_name='Pacote')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='id_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.service', verbose_name='Serviço'),
        ),
    ]
