# Generated by Django 4.2.1 on 2024-09-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_treatment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do atendimento'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='status',
            field=models.CharField(choices=[('1', 'Agendado'), ('2', 'Concluído'), ('3', 'Cancelado')], default='2', max_length=1, verbose_name='Status'),
        ),
    ]
