# Generated by Django 4.2.16 on 2024-10-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_alter_treatment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('created_at',), 'verbose_name': 'Pacote', 'verbose_name_plural': 'Lista de Pacotes'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Meus Serviços'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('date',), 'verbose_name': 'Sessão', 'verbose_name_plural': 'Sessões'},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ('created_at',), 'verbose_name': 'Atendimento', 'verbose_name_plural': 'Lista de Atendimentos'},
        ),
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(verbose_name='Data'),
        ),
    ]
