# Generated by Django 4.2.16 on 2024-10-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_package_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do atendimento'),
        ),
    ]
