# Generated by Django 4.2.16 on 2024-10-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_alter_session_options_session_force_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='force_save',
        ),
    ]
