# Generated by Django 4.2.16 on 2024-10-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_remove_session_force_save'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': [models.OrderBy(models.F('date'), nulls_last=True)], 'verbose_name': 'Sessão', 'verbose_name_plural': 'Sessões'},
        ),
        migrations.AddField(
            model_name='treatment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
