# Generated by Django 4.2.16 on 2024-10-09 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_alter_session_options_treatment_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('created_at',), 'verbose_name': 'Pacote', 'verbose_name_plural': 'Pacotes de atendimentos'},
        ),
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ('created_at',), 'verbose_name': 'Atendimento', 'verbose_name_plural': 'Atendimentos únicos'},
        ),
    ]
