# Generated by Django 4.2.16 on 2024-10-04 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_client_created_at_client_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_indicator_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.client', verbose_name='Indicado por'),
        ),
    ]
