# Generated by Django 4.2.16 on 2024-10-04 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_client_id_indicator_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_indicator_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.client', verbose_name='Indicado(a) por'),
        ),
    ]
