# Generated by Django 4.2.16 on 2024-10-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_alter_client_id_indicator_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professional',
            options={'verbose_name': 'Profissional', 'verbose_name_plural': 'Perfil Profissional'},
        ),
        migrations.AlterField(
            model_name='professional',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Telefone (WhatsApp)'),
        ),
    ]
