# Generated by Django 4.2.16 on 2024-10-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_alter_client_cpf_alter_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Nome'),
        ),
    ]
