# Generated by Django 4.2.16 on 2024-10-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_alter_professional_cpf_alter_professional_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('cpf', 'id_professional'), name='unique_cpf_by_professional'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('email', 'id_professional'), name='unique_email_by_professional'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('phone', 'id_professional'), name='unique_phone_by_professional'),
        ),
    ]
