# Generated by Django 4.2.16 on 2024-10-04 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0007_alter_client_id_indicator_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicationCouponConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_indication_coupon', models.BooleanField(default=False, verbose_name='Habilitar Cupom de Indicação')),
                ('type_discount', models.CharField(choices=[('1', 'Valor de desconto'), ('2', 'Porcentagem de desconto')], default='1', max_length=1, verbose_name='Tipo de Desconto')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor do Desconto')),
                ('discount_percentage', models.IntegerField(blank=True, null=True, verbose_name='Porcentagem de Desconto')),
                ('valid_days', models.IntegerField(blank=True, null=True, verbose_name='Dias de Validade')),
                ('max_value_discount', models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=5, null=True, verbose_name='Valor Máximo do Desconto')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Atualização')),
                ('id_professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.professional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Configurações do Cupom por Indicação',
            },
        ),
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Código')),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Valor do Desconto')),
                ('discount_percentage', models.IntegerField(blank=True, null=True, verbose_name='Porcentagem de Desconto')),
                ('used', models.BooleanField(default=False, verbose_name='Usado')),
                ('cancelled', models.BooleanField(default=False, verbose_name='Cancelado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de Atualização')),
                ('id_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.client', verbose_name='Cliente')),
                ('id_professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.professional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Cupom de Desconto',
                'verbose_name_plural': 'Cupons de Desconto',
            },
        ),
    ]
