# Generated by Django 4.2.16 on 2024-10-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicationcouponconfiguration',
            options={'verbose_name': 'Configurações do Cupom por Indicação', 'verbose_name_plural': 'Configurações dos Cupons por Indicação'},
        ),
        migrations.AddField(
            model_name='discountcoupon',
            name='type_discount',
            field=models.CharField(choices=[('1', 'Valor de desconto'), ('2', 'Porcentagem de desconto')], default='1', max_length=1, verbose_name='Tipo de Desconto'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='cancelled',
            field=models.BooleanField(default=False, verbose_name='Desabilitar cupom'),
        ),
    ]
