# Generated by Django 4.2.16 on 2024-10-04 17:53

from django.db import migrations, models
import finances.models.discount_coupon


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_indicationcouponconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcoupon',
            name='max_value_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=5, null=True, verbose_name='Valor Máximo do Desconto'),
        ),
        migrations.AddField(
            model_name='discountcoupon',
            name='valid_days',
            field=models.IntegerField(blank=True, help_text='Prazo de validade do cupom em dias', null=True, verbose_name='Dias de Validade'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='cancelled',
            field=models.BooleanField(default=False, verbose_name='Cupom encerrado'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='code',
            field=models.CharField(default=finances.models.discount_coupon.generate_random_code, max_length=20, verbose_name='Código'),
        ),
    ]
