# Generated by Django 4.2.16 on 2024-10-04 20:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_alter_professional_options_alter_professional_phone'),
        ('finances', '0003_discountcoupon_max_value_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicationcouponconfiguration',
            options={'verbose_name': 'Config. do Cupom por Indicação', 'verbose_name_plural': 'Config. dos Cupons por Indicação'},
        ),
        migrations.AddField(
            model_name='discountcoupon',
            name='coupon_usage_limit',
            field=models.PositiveIntegerField(default=1, help_text='Número máximo de vezes que o cupom pode ser utilizado, uma vez por cliente.', verbose_name='Limite de Uso do Cupom'),
        ),
        migrations.AddField(
            model_name='discountcoupon',
            name='specific_client',
            field=models.BooleanField(default=False, help_text='Marque se este cupom for destinado a um cliente específico.', verbose_name='Redirecionar para Cliente Específico?'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='cancelled',
            field=models.BooleanField(default=False, help_text='Cupons encerrados não podem ser utilizados', verbose_name='Cupom encerrado'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='id_client',
            field=models.ForeignKey(blank=True, help_text='O cliente poderá usar o cupom somente uma vez.', null=True, on_delete=django.db.models.deletion.CASCADE, to='person.client', verbose_name='Cliente Ganhador do Cupom'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='used',
            field=models.BooleanField(default=False, help_text='Cupons usados não podem ser utilizados novamente', verbose_name='Usado'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='valid_days',
            field=models.IntegerField(blank=True, help_text='Prazo de validade do cupom em dias, deixe em branco para não expirar', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dias de Validade'),
        ),
        migrations.AlterField(
            model_name='indicationcouponconfiguration',
            name='max_value_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, help_text='Valor máximo do desconto permitido', max_digits=5, null=True, verbose_name='Valor Máximo do Desconto'),
        ),
        migrations.AlterField(
            model_name='indicationcouponconfiguration',
            name='valid_days',
            field=models.IntegerField(blank=True, help_text='Prazo de validade do cupom em dias, deixe em branco para não expirar', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dias de Validade'),
        ),
    ]
